package com.example.learntodrawpvz.entities

import com.example.learntodrawpvz.Constants

enum class PvZ(val pvZModel: PvZModel) {
    PvZ1(
        Constants.getPvZ(1)
    ),
    PvZ2(
        Constants.getPvZ(2)
    ),
    PvZ3(
        Constants.getPvZ(3)
    ),
    PvZ4(
        Constants.getPvZ(4)
    ),
    PvZ5(
        Constants.getPvZ(5)
    ),
    PvZ6(
        Constants.getPvZ(6)
    ),
    PvZ7(
        Constants.getPvZ(7)
    ),
    PvZ8(
        Constants.getPvZ(8)
    ),
    PvZ9(
        Constants.getPvZ(9)
    ),
    PvZ10(
        Constants.getPvZ(10)
    ),
    PvZ11(
        Constants.getPvZ(11)
    ),
    PvZ12(
        Constants.getPvZ(12)
    ),
    PvZ13(
        Constants.getPvZ(13)
    ),
    PvZ14(
        Constants.getPvZ(14)
    ),
    PvZ15(
        Constants.getPvZ(15)
    ),
    PvZ16(
        Constants.getPvZ(16)
    ),
    PvZ17(
        Constants.getPvZ(17)
    ),
    PvZ18(
        Constants.getPvZ(18)
    ),
    PvZ19(
        Constants.getPvZ(19)
    ),
    PvZ20(
        Constants.getPvZ(20)
    ),
    PvZ21(
        Constants.getPvZ(21)
    ),
    PvZ22(
        Constants.getPvZ(22)
    ),
    PvZ23(
        Constants.getPvZ(23)
    ),
    PvZ24(
        Constants.getPvZ(24)
    ),
    PvZ25(
        Constants.getPvZ(25)
    ),
    PvZ26(
        Constants.getPvZ(26)
    ),
    PvZ27(
        Constants.getPvZ(27)
    ),
    PvZ28(
        Constants.getPvZ(28)
    )
}